version: '3.3'

services:
  app:
    build:
      context: .
    ports:
      - 8000:5000
    volumes: 
      - ./:/app

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
